#!/usr/bin/env bash
#
# azureredops.sh — manage the AzureRedOps Console Docker stack
# (PostgreSQL + FastAPI backend + React frontend + remote MCP server).
#
# Usage: ./azureredops.sh <command> [options]
# Run `./azureredops.sh help` for the full command list.
#
set -euo pipefail

# --------------------------------------------------------------------------- #
# Setup: always operate from the repo root (this script's directory).
# --------------------------------------------------------------------------- #
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

ENV_FILE=".env"
BACKUP_DIR="backups"
PROJECT_NAME="$(basename "$SCRIPT_DIR" | tr '[:upper:]' '[:lower:]')"

# Colors (disabled if not a TTY)
if [[ -t 1 ]]; then
  C_RED=$'\033[31m'; C_GRN=$'\033[32m'; C_YEL=$'\033[33m'; C_BLU=$'\033[34m'
  C_BOLD=$'\033[1m'; C_DIM=$'\033[2m'; C_RST=$'\033[0m'
else
  C_RED=""; C_GRN=""; C_YEL=""; C_BLU=""; C_BOLD=""; C_DIM=""; C_RST=""
fi

info() { printf '%s==>%s %s\n' "$C_BLU"  "$C_RST" "$*"; }
ok()   { printf '%s[ok]%s %s\n' "$C_GRN" "$C_RST" "$*"; }
warn() { printf '%s[!]%s %s\n'  "$C_YEL" "$C_RST" "$*"; }
errln(){ printf '%s[x]%s %s\n'  "$C_RED" "$C_RST" "$*" >&2; }
die()  { errln "$*"; exit 1; }

# --------------------------------------------------------------------------- #
# Compose command detection (docker compose v2 preferred, docker-compose v1 fb)
# --------------------------------------------------------------------------- #
detect_compose() {
  if docker compose version >/dev/null 2>&1; then
    DC=(docker compose)
  elif command -v docker-compose >/dev/null 2>&1; then
    DC=(docker-compose)
  else
    die "Docker Compose not found. Install Docker Desktop or the compose plugin."
  fi
  docker info >/dev/null 2>&1 || die "Docker daemon is not running. Start Docker and retry."
}

dc() { "${DC[@]}" "$@"; }

# --------------------------------------------------------------------------- #
# Helpers
# --------------------------------------------------------------------------- #
# env_get KEY [default] — read a value from .env
env_get() {
  local key="$1" def="${2:-}"
  if [[ -f "$ENV_FILE" ]]; then
    local line
    line="$(grep -E "^${key}=" "$ENV_FILE" | tail -n1 || true)"
    if [[ -n "$line" ]]; then printf '%s' "${line#*=}"; return; fi
  fi
  printf '%s' "$def"
}

require_env() {
  [[ -f "$ENV_FILE" ]] || die "No .env found. Run: ./azureredops.sh init-secrets"
}

# gen_token N — URL-safe random token of ~N bytes entropy
gen_token() {
  python3 -c "import secrets;print(secrets.token_urlsafe(${1}))" 2>/dev/null \
    || openssl rand -hex "${1}"
}
# gen_fernet — 32-byte urlsafe-base64 key (valid Fernet key); blank on failure
gen_fernet() {
  python3 -c "import os,base64;print(base64.urlsafe_b64encode(os.urandom(32)).decode())" 2>/dev/null || true
}

confirm() {
  # confirm "message"  -> respects --yes/-y via $ASSUME_YES
  local msg="$1"
  if [[ "${ASSUME_YES:-0}" == "1" ]]; then return 0; fi
  printf '%s%s%s [y/N] ' "$C_YEL" "$msg" "$C_RST"
  read -r reply || true
  [[ "$reply" =~ ^[Yy]$ ]]
}

db_volume_exists() {
  docker volume ls --format '{{.Name}}' 2>/dev/null | grep -q "${PROJECT_NAME}_pgdata"
}

# --------------------------------------------------------------------------- #
# Commands
# --------------------------------------------------------------------------- #
cmd_init_secrets() {
  local force=0
  for a in "$@"; do [[ "$a" == "--force" || "$a" == "-f" ]] && force=1; done

  if [[ -f "$ENV_FILE" && "$force" != "1" ]]; then
    die ".env already exists. Use 'init-secrets --force' to regenerate (existing is backed up to .env.bak)."
  fi
  if [[ -f "$ENV_FILE" ]]; then
    cp "$ENV_FILE" ".env.bak"
    warn "Existing .env backed up to .env.bak"
  fi
  if db_volume_exists; then
    warn "A database volume already exists. New POSTGRES_PASSWORD won't apply until the"
    warn "volume is recreated (run 'nuke' first), or Postgres auth may fail."
  fi

  info "Generating secrets..."
  local pgpass secret vault adminpass mcpkey
  pgpass="$(gen_token 24)"
  secret="$(gen_token 48)"
  vault="$(gen_fernet)"
  adminpass="$(gen_token 18)"
  mcpkey="$(gen_token 32)"

  # Preserve some existing non-secret prefs if regenerating
  local web_port mcp_port admin_user
  web_port="$(env_get WEB_PORT 8080)"
  mcp_port="$(env_get MCP_PORT 9090)"
  admin_user="$(env_get ADMIN_USERNAME admin)"

  umask 077
  cat > "$ENV_FILE" <<EOF
# Generated by azureredops.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ"). DO NOT COMMIT (gitignored).

# --- Web ---
WEB_PORT=${web_port}

# --- Postgres ---
POSTGRES_USER=azureredops
POSTGRES_PASSWORD=${pgpass}
POSTGRES_DB=azureredops

# --- Backend security ---
SECRET_KEY=${secret}
VAULT_KEY=${vault}

# --- Initial admin account (created on first start) ---
ADMIN_USERNAME=${admin_user}
ADMIN_PASSWORD=${adminpass}
ACCESS_TOKEN_MINUTES=720
CORS_ORIGINS=*

# --- MCP server (remote, Streamable HTTP transport) ---
MCP_PORT=${mcp_port}
MCP_API_KEY=${mcpkey}
EOF
  chmod 600 "$ENV_FILE"

  ok ".env written (chmod 600)."
  if [[ -n "$vault" ]]; then ok "VAULT_KEY: dedicated Fernet key generated."
  else warn "VAULT_KEY left blank (backend will derive one from SECRET_KEY)."; fi
  echo
  printf '%s== Credentials you need ==%s\n' "$C_BOLD" "$C_RST"
  printf '  Console UI    : http://localhost:%s\n' "$web_port"
  printf '  Console login : %s / %s\n' "$admin_user" "$adminpass"
  printf '  MCP endpoint  : http://127.0.0.1:%s/mcp\n' "$mcp_port"
  printf '  MCP_API_KEY   : %s\n' "$mcpkey"
  echo
  warn "These are also stored in .env. Run 'creds' or 'mcp-info' to print them again."
}

cmd_up() {
  require_env
  local build=0
  for a in "$@"; do [[ "$a" == "--build" ]] && build=1; done
  if [[ "$build" == "1" ]]; then
    info "Building images and starting the stack..."
    dc up -d --build
  else
    info "Starting the stack..."
    dc up -d
  fi
  ok "Stack is up."
  cmd_status
}

cmd_down() {
  detect_compose
  info "Stopping the stack (data volumes preserved)..."
  dc down "$@"
  ok "Stack stopped."
}

cmd_restart() {
  require_env
  if [[ $# -gt 0 ]]; then
    info "Restarting service(s): $*"
    dc restart "$@"
  else
    info "Restarting all services..."
    dc restart
  fi
  ok "Restarted."
}

cmd_build() {
  require_env
  info "Building images..."
  dc build "$@"
  ok "Build complete."
}

cmd_update() {
  require_env
  info "Pulling base images and rebuilding..."
  dc build --pull
  info "Recreating containers..."
  dc up -d
  ok "Update complete."
  cmd_status
}

cmd_nuke() {
  detect_compose
  local rmi=""
  for a in "$@"; do [[ "$a" == "--images" ]] && rmi="--rmi local"; done
  warn "This removes all containers AND the database volume (ALL DATA IS LOST)."
  if ! confirm "Nuke the stack?"; then info "Aborted."; return 0; fi
  # shellcheck disable=SC2086
  dc down -v --remove-orphans $rmi || true
  ok "Stack nuked (containers + volumes removed)."
}

cmd_status() {
  detect_compose
  info "Services:"
  dc ps
  echo
  local web mcp
  web="$(env_get WEB_PORT 8080)"; mcp="$(env_get MCP_PORT 9090)"
  printf '  %sWeb UI%s   http://localhost:%s\n' "$C_DIM" "$C_RST" "$web"
  printf '  %sMCP%s      http://127.0.0.1:%s/mcp\n' "$C_DIM" "$C_RST" "$mcp"
}

cmd_logs() {
  detect_compose
  dc logs "$@"
}

cmd_health() {
  detect_compose
  local web mcp pu pdb code
  web="$(env_get WEB_PORT 8080)"; mcp="$(env_get MCP_PORT 9090)"
  pu="$(env_get POSTGRES_USER azureredops)"; pdb="$(env_get POSTGRES_DB azureredops)"

  printf '%s== Health ==%s\n' "$C_BOLD" "$C_RST"

  # DB
  if dc exec -T db pg_isready -U "$pu" -d "$pdb" >/dev/null 2>&1; then
    ok "db        : accepting connections"
  else
    errln "db        : not ready"
  fi

  # Backend (via the nginx /api proxy on the web port)
  code="$(curl -fsS -o /dev/null -w '%{http_code}' "http://localhost:${web}/api/health" 2>/dev/null || echo 000)"
  if [[ "$code" == "200" ]]; then ok "backend   : /api/health 200 (via web proxy)"
  else errln "backend   : /api/health -> HTTP $code"; fi

  # MCP (any HTTP status means it's listening; 401 = bearer gate working)
  code="$(curl -s -o /dev/null -w '%{http_code}' "http://127.0.0.1:${mcp}/mcp" 2>/dev/null || echo 000)"
  case "$code" in
    000) errln "mcp       : not reachable on 127.0.0.1:${mcp}" ;;
    401) ok    "mcp       : listening (HTTP 401 — bearer token required, good)" ;;
    *)   ok    "mcp       : listening (HTTP $code)" ;;
  esac
}

cmd_backup() {
  detect_compose
  local pu pdb out
  pu="$(env_get POSTGRES_USER azureredops)"; pdb="$(env_get POSTGRES_DB azureredops)"
  mkdir -p "$BACKUP_DIR"
  out="${1:-$BACKUP_DIR/azureredops-$(date +%Y%m%d-%H%M%S).dump}"
  info "Backing up database '$pdb' -> $out"
  dc exec -T db pg_dump -U "$pu" -d "$pdb" -Fc > "$out" \
    || die "pg_dump failed (is the stack up?)"
  ok "Backup written: $out ($(du -h "$out" | cut -f1))"
}

cmd_restore() {
  detect_compose
  local file="${1:-}"
  [[ -n "$file" ]] || die "Usage: restore <backup-file.dump>"
  [[ -f "$file" ]] || die "File not found: $file"
  local pu pdb
  pu="$(env_get POSTGRES_USER azureredops)"; pdb="$(env_get POSTGRES_DB azureredops)"
  warn "This will OVERWRITE the current contents of database '$pdb'."
  if ! confirm "Restore from $file?"; then info "Aborted."; return 0; fi
  info "Restoring..."
  dc exec -T db pg_restore -U "$pu" -d "$pdb" --clean --if-exists --no-owner < "$file" \
    || warn "pg_restore reported errors (often harmless --clean notices)."
  ok "Restore complete."
}

cmd_rotate_mcp_key() {
  require_env
  local newkey; newkey="$(gen_token 32)"
  cp "$ENV_FILE" ".env.bak"
  # portable in-place replace of MCP_API_KEY line
  if grep -qE '^MCP_API_KEY=' "$ENV_FILE"; then
    grep -vE '^MCP_API_KEY=' "$ENV_FILE" > "$ENV_FILE.tmp"
    printf 'MCP_API_KEY=%s\n' "$newkey" >> "$ENV_FILE.tmp"
    mv "$ENV_FILE.tmp" "$ENV_FILE"
  else
    printf 'MCP_API_KEY=%s\n' "$newkey" >> "$ENV_FILE"
  fi
  chmod 600 "$ENV_FILE"
  ok "MCP_API_KEY rotated (old .env saved to .env.bak)."
  printf '  New MCP_API_KEY: %s\n' "$newkey"
  if dc ps --services --filter status=running 2>/dev/null | grep -qx mcp; then
    info "Recreating the mcp service to apply the new key..."
    dc up -d mcp
    ok "mcp restarted."
  else
    warn "Start/recreate the stack for the new key to take effect (up / restart mcp)."
  fi
}

cmd_creds() {
  require_env
  printf '%s== AzureRedOps stack ==%s\n' "$C_BOLD" "$C_RST"
  printf '  Console UI    : http://localhost:%s\n' "$(env_get WEB_PORT 8080)"
  printf '  Console login : %s / %s\n' "$(env_get ADMIN_USERNAME admin)" "$(env_get ADMIN_PASSWORD '?')"
  printf '  MCP endpoint  : http://127.0.0.1:%s/mcp\n' "$(env_get MCP_PORT 9090)"
  printf '  MCP_API_KEY   : %s\n' "$(env_get MCP_API_KEY '?')"
}

cmd_mcp_info() {
  require_env
  local mcp key
  mcp="$(env_get MCP_PORT 9090)"; key="$(env_get MCP_API_KEY '?')"
  printf '%s== MCP server connection ==%s\n' "$C_BOLD" "$C_RST"
  printf '  Endpoint : http://127.0.0.1:%s/mcp  (Streamable HTTP, localhost only)\n' "$mcp"
  printf '  Header   : Authorization: Bearer %s\n\n' "$key"
  printf '%sClaude Code:%s\n' "$C_DIM" "$C_RST"
  printf '  claude mcp add --transport http azureredops http://127.0.0.1:%s/mcp \\\n' "$mcp"
  printf '    --header "Authorization: Bearer %s"\n\n' "$key"
  printf '%s.mcp.json:%s\n' "$C_DIM" "$C_RST"
  cat <<EOF
  {
    "mcpServers": {
      "azureredops": {
        "type": "http",
        "url": "http://127.0.0.1:${mcp}/mcp",
        "headers": { "Authorization": "Bearer ${key}" }
      }
    }
  }
EOF
}

cmd_psql() {
  detect_compose
  local pu pdb
  pu="$(env_get POSTGRES_USER azureredops)"; pdb="$(env_get POSTGRES_DB azureredops)"
  "${DC[@]}" exec db psql -U "$pu" -d "$pdb"
}

cmd_shell() {
  detect_compose
  local svc="${1:-backend}"
  info "Opening a shell in '$svc' (sh)..."
  "${DC[@]}" exec "$svc" /bin/sh
}

cmd_run_in() {
  detect_compose
  [[ $# -ge 2 ]] || die "Usage: exec <service> <command...>"
  local svc="$1"; shift
  dc exec "$svc" "$@"
}

cmd_config() {
  detect_compose
  dc config "$@"
}

cmd_open() {
  local url="http://localhost:$(env_get WEB_PORT 8080)"
  info "Opening $url"
  if command -v open >/dev/null 2>&1; then open "$url"
  elif command -v xdg-open >/dev/null 2>&1; then xdg-open "$url"
  else echo "$url"; fi
}

cmd_help() {
  cat <<EOF
${C_BOLD}azureredops.sh${C_RST} — manage the AzureRedOps Console Docker stack

${C_BOLD}Lifecycle${C_RST}
  up [--build]        Start the stack (detached). --build to (re)build first.
  down [args...]      Stop & remove containers (data volumes kept).
  restart [svc...]    Restart all services, or only the named ones.
  build [args...]     Build images (e.g. 'build --no-cache').
  update              Pull base images, rebuild, recreate containers.
  nuke [--images]     Stop & remove containers AND volumes (DESTROYS DATA).
                      --images also removes locally built images.

${C_BOLD}Secrets & info${C_RST}
  init-secrets [-f]   Generate a fresh .env with strong secrets (-f to overwrite).
  rotate-mcp-key      Generate a new MCP_API_KEY and recreate the mcp service.
  creds               Print console login + MCP key + URLs.
  mcp-info            Print MCP endpoint + ready-to-paste client config.

${C_BOLD}Operations${C_RST}
  status              Show service status and URLs.
  health              Check db / backend / mcp health.
  logs [svc] [-f]     Show (or follow with -f) logs.
  backup [file]       pg_dump the database (default: backups/<timestamp>.dump).
  restore <file>      Restore the database from a dump (overwrites current data).
  psql                Open a psql shell on the database.
  shell [svc]         Open a shell in a service container (default: backend).
  exec <svc> <cmd>    Run a command in a service container.
  config [args...]    Validate / print the resolved compose config.
  open                Open the Console web UI in your browser.

${C_DIM}Global: pass --yes (or -y) to skip confirmation prompts (nuke, restore).${C_RST}

Examples:
  ./azureredops.sh init-secrets
  ./azureredops.sh up --build
  ./azureredops.sh health
  ./azureredops.sh backup
EOF
}

# --------------------------------------------------------------------------- #
# Dispatch
# --------------------------------------------------------------------------- #
main() {
  # Extract global --yes/-y anywhere in args
  local args=()
  for a in "$@"; do
    case "$a" in
      --yes|-y) ASSUME_YES=1 ;;
      *) args+=("$a") ;;
    esac
  done
  set -- "${args[@]:-}"

  local cmd="${1:-help}"; shift || true

  case "$cmd" in
    up)             detect_compose; cmd_up "$@" ;;
    down)           cmd_down "$@" ;;
    restart)        detect_compose; cmd_restart "$@" ;;
    build)          detect_compose; cmd_build "$@" ;;
    update)         detect_compose; cmd_update "$@" ;;
    nuke)           cmd_nuke "$@" ;;
    init-secrets)   cmd_init_secrets "$@" ;;
    rotate-mcp-key) detect_compose; cmd_rotate_mcp_key "$@" ;;
    creds)          cmd_creds ;;
    mcp-info)       cmd_mcp_info ;;
    status|ps)      cmd_status ;;
    health)         cmd_health ;;
    logs)           cmd_logs "$@" ;;
    backup)         cmd_backup "$@" ;;
    restore)        cmd_restore "$@" ;;
    psql)           cmd_psql ;;
    shell)          cmd_shell "$@" ;;
    exec)           cmd_run_in "$@" ;;
    config)         cmd_config "$@" ;;
    open)           cmd_open ;;
    help|-h|--help) cmd_help ;;
    *)              errln "Unknown command: $cmd"; echo; cmd_help; exit 1 ;;
  esac
}

main "$@"
