"""Describes every operation so the frontend can render input forms dynamically."""

# field types: text, password, textarea, number, bool, token, select
def _field(name, label, ftype="text", required=False, placeholder="", help="",
           default=None, options=None):
    return {"name": name, "label": label, "type": ftype, "required": required,
            "placeholder": placeholder, "help": help, "default": default,
            "options": options or []}


TOKEN_FIELD = _field("token_id", "Vault token", "token", required=True,
                     help="Pick a stored token, or paste a raw access token below.")
RAW_TOKEN = _field("access_token", "Raw access token (optional)", "textarea",
                   help="Overrides the vault selection if provided.")
VERSION_FIELD = _field("version", "API version", "select", default="v2.0",
                       options=["v2.0", "v0"])

CATALOG = [
    {
        "key": "recon", "title": "Reconnaissance",
        "operations": [
            {"activity": "id", "name": "Tenant ID lookup", "long_running": False,
             "description": "Resolve the Azure tenant ID from a domain name.",
             "fields": [_field("tenant", "Tenant domain", required=True,
                               placeholder="contoso.com")]},
            {"activity": "self", "name": "Whoami (/me)", "long_running": False,
             "description": "Read the current user's Graph profile.",
             "fields": [TOKEN_FIELD, RAW_TOKEN]},
            {"activity": "permission", "name": "Authorization policy", "long_running": False,
             "description": "Read the tenant authorization policy (beta).",
             "fields": [TOKEN_FIELD, RAW_TOKEN]},
            {"activity": "email", "name": "Search mailbox", "long_running": False,
             "description": "Search the current user's email.",
             "fields": [TOKEN_FIELD, RAW_TOKEN,
                        _field("filter", "Search term", required=True, placeholder="password")]},
            {"activity": "list-users", "name": "List users", "long_running": True,
             "description": "Enumerate directory users (paginated).",
             "fields": [TOKEN_FIELD, RAW_TOKEN,
                        _field("filter", "OData filter (optional)", placeholder="?$top=50")]},
            {"activity": "list-applications", "name": "List applications", "long_running": True,
             "description": "Enumerate app registrations (paginated).",
             "fields": [TOKEN_FIELD, RAW_TOKEN,
                        _field("filter", "OData filter (optional)")]},
            {"activity": "list-principals", "name": "List service principals", "long_running": True,
             "description": "Enumerate service principals (paginated).",
             "fields": [TOKEN_FIELD, RAW_TOKEN]},
            {"activity": "gather-all", "name": "Gather everything", "long_running": True,
             "description": "Dump org, policies, users, groups, apps, grants, principals, roles.",
             "fields": [TOKEN_FIELD, RAW_TOKEN]},
            {"activity": "raw-url", "name": "Raw Graph URL", "long_running": True,
             "description": "GET an arbitrary Graph URL (follows pagination).",
             "fields": [TOKEN_FIELD, RAW_TOKEN,
                        _field("url", "Graph URL", required=True,
                               placeholder="https://graph.microsoft.com/beta/users")]},
            {"activity": "magic-app", "name": "Magic app finder", "long_running": True,
             "description": "Find public-client apps with AllPrincipals consent and no assignment requirement.",
             "fields": [TOKEN_FIELD, RAW_TOKEN]},
            {"activity": "inspect-token", "name": "Inspect token (decode JWT)", "long_running": False,
             "description": "Decode a token's claims locally.",
             "fields": [TOKEN_FIELD, RAW_TOKEN]},
        ],
    },
    {
        "key": "auth", "title": "Authentication",
        "operations": [
            {"activity": "auth", "name": "Password (ROPC)", "long_running": False,
             "description": "Authenticate with username/password (resource owner password credentials).",
             "fields": [_field("username", "Username (UPN)", required=True),
                        _field("password", "Password", "password", required=True),
                        _field("tenant", "Tenant", required=True, placeholder="contoso.com or GUID"),
                        _field("appid", "App ID (optional)"), VERSION_FIELD]},
            {"activity": "phish-start", "name": "Device code: start", "long_running": False,
             "description": "Generate a device code to present to a target.",
             "fields": [_field("tenant", "Tenant (optional)", placeholder="common"),
                        _field("appid", "App ID (optional)")]},
            {"activity": "phish-capture", "name": "Device code: capture", "long_running": True,
             "description": "Poll for the token after the target authenticates. Cancellable.",
             "fields": [_field("device_code", "Device code", required=True),
                        _field("tenant", "Tenant (optional)", placeholder="common"),
                        _field("appid", "App ID (optional)")]},
            {"activity": "refresh", "name": "Refresh token", "long_running": False,
             "description": "Exchange a refresh token for a fresh access token.",
             "fields": [TOKEN_FIELD,
                        _field("refresh_token", "Raw refresh token (optional)", "textarea"),
                        _field("tenant", "Tenant (if raw)", placeholder="contoso.com or GUID"),
                        _field("appid", "App ID (optional)"), VERSION_FIELD]},
            {"activity": "auth-app", "name": "PKCE browser flow", "long_running": True,
             "description": "Generate a consent URL and capture the auth code on the local TLS callback.",
             "fields": [_field("tenant", "Tenant (optional)", placeholder="common"),
                        _field("appid", "App ID (optional)"),
                        _field("timeout", "Timeout (s)", "number", default=300)]},
            {"activity": "auth-interactive", "name": "Interactive (Playwright + HAR)", "long_running": True,
             "description": "Spawn a browser, authenticate, scrape tokens from the session HAR. Requires the Playwright display.",
             "fields": [_field("url", "Target URL(s), comma-separated", required=True,
                               default="https://portal.azure.com"),
                        _field("delay", "Auth wait (s)", "number", default=75)]},
        ],
    },
    {
        "key": "spray", "title": "Password Spraying",
        "operations": [
            {"activity": "spray", "name": "Spray (password)", "long_running": True,
             "description": "Spray a username/password across many first-party client IDs. Cancellable.",
             "fields": [_field("username", "Username (UPN)", required=True),
                        _field("password", "Password", "password", required=True),
                        _field("tenant", "Tenant", required=True),
                        _field("check_privileges", "Check privileges on success", "bool", default=False)]},
            {"activity": "spray-refresh", "name": "Spray (refresh token)", "long_running": True,
             "description": "Replay a refresh token across many client IDs. Cancellable.",
             "fields": [TOKEN_FIELD,
                        _field("refresh_token", "Raw refresh token (optional)", "textarea"),
                        _field("tenant", "Tenant (if raw)"),
                        _field("check_privileges", "Check privileges on success", "bool", default=False)]},
        ],
    },
    {
        "key": "actions", "title": "Privilege / Persistence Actions",
        "operations": [
            {"activity": "register-app", "name": "Register application", "long_running": False,
             "description": "Create a new app registration with a client secret.",
             "fields": [TOKEN_FIELD, RAW_TOKEN, _field("name", "Display name", required=True)]},
            {"activity": "new-group", "name": "Create group", "long_running": False,
             "description": "Create a new security group.",
             "fields": [TOKEN_FIELD, RAW_TOKEN, _field("name", "Group name", required=True)]},
            {"activity": "add-group", "name": "Assign directory role", "long_running": False,
             "description": "Assign a role (default: Global Administrator) to a principal.",
             "fields": [TOKEN_FIELD, RAW_TOKEN,
                        _field("uid", "Principal (user) ID", required=True),
                        _field("gid", "Role definition ID (optional)",
                               placeholder="62e90394-69f5-4237-91f9-056ad24d70a7")]},
            {"activity": "invite", "name": "Invite external user", "long_running": False,
             "description": "Send a B2B guest invitation.",
             "fields": [TOKEN_FIELD, RAW_TOKEN,
                        _field("email", "Email to invite", required=True),
                        _field("url", "Redirect URL (optional)")]},
            {"activity": "push-file", "name": "Upload file to OneDrive", "long_running": False,
             "description": "Upload arbitrary content to the user's OneDrive.",
             "fields": [TOKEN_FIELD, RAW_TOKEN,
                        _field("name", "Remote filename", required=True, placeholder="notes.txt"),
                        _field("content", "File content", "textarea", required=True)]},
        ],
    },
]
